# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TableViewDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'Moya/RxSwift'
  pod 'Moya-ObjectMapper/RxSwift'
  pod 'ObjectMapper'
  # Pods for TableViewDemo
  
end
